apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  -    name: mysql-secret
       literals:
        -   password=redhat123
        -   userpass=nishant123
resources:
   -    efs-provisioner.yml
   -    role.yml
   -    storage.yml
   -    deploy-mysql.yml
   -    deploy-joomla.yml